[capital_com]
X_CAP_API_KEY = "MKDM5l391KGb5eo9"
identifier = "arshad.emad@gmail.com"
password = "Quiteneat@3"

[gemini]
api_keys = [
    "AIzaSyAqpeu5F69PkcggYFjRk5saI-NqEu6sK_0",
    "AIzaSyB9c_F5ma0zWzkILWjGKj9EnSFLQpd-zKw",
    "AIzaSyAxg5Keaofj9EGmUB5llDL2aRMEqqAcv5g",
    "AIzaSyCaQdJRth9rS3cxSSpPvyqjO2GodFEDIgw",
    "AIzaSyAh8gFjqR5GRLYtY8OUiCk1E4Wx8vp53JQ",
    "AIzaSyByK1W-BHb9cP93wfxKe1ZOk8ZRCt1Ly38",
    "AIzaSyAtubEXxMoRiYxD7SoqhM8weYuD7wvwQ5o",
    "AIzaSyCfhofgxhdvf-5yb1OzoARN6mR77HKuUyI",
    "AIzaSyBIBhEXKz5kM66z4wZqi6aQsl1JrJerMQc",
    "AIzaSyAnuUX6h-GwTKzT3w461T-FiZVGi1X4TBQ",
    "AIzaSyDxrevk9UOiuFjc-2637s-vXbOkQLHqOmw",
    "AIzaSyDzgnHoJwVVyOar-276d8pILFIG_DWLGfM",
    "AIzaSyBGxmdYoW6ZVhgdG0Tz0jHgcgsLqC2IdUc",
    "AIzaSyDrQYFVXHQ6W1WWBhkbvMit3qkS-Ltg4wc",
    "AIzaSyBwbkmGcpniIvoTFUpo9a5ozyO3wGJskXs",
    "AIzaSyDLrocPTJ4Y2KbFVYOs2TeihJ49FBrsgrU",
    "AIzaSyB72L5ESK0s4kdYdzu43P1c25wJh7HzTp8",
    "AIzaSyB5xJtc_ItiI2yQMHXJ80-BWPAJiwaGIqY",
    "AIzaSyDnWSVoWR59yEjRd6Q1H2yERcNHDxd-WOM",
    "AIzaSyCTQcgHfrq0lhvxeWvmGH-6HX3RYEc4g4w",
    "AIzaSyDym_hiyACZCH2Ww5jRdRwD0BBrKVzX3Zk",
    "AIzaSyDyL_G7NLgrUVe28jVCcBYVGBRvkvNv3j0",
    "AIzaSyCyqxaqM6b8EihuYVuZcyJCPDQRK8GaHOY",
    "AIzaSyCVMoQ0LZ9MUlw5Q-B7FmMnLPiS1lSOX1E",
    "AIzaSyAjdbxnBaaMjxXC-433glS7mQzZFhjTJVY",
    "AIzaSyBxn4ghDbOpY1TBCp0K-idp3a0xao-cmF8",
    "AIzaSyDf1I3M4F-4JZWWn6h32jIgdCDEES0bin0",
    "AIzaSyBBdXvUWvqPcUxpYTRQCZOENcFcCaT9__E",
    "AIzaSyC3x7pdtEjuu4su_TULwliWCPi21_bAL4Q",
    "AIzaSyDYD8BMvZ-E4vnI7X1idg2BeMn1JH4-utM",
    "AIzaSyAYMVyXxG-X4tPo4WK6dMIK9hfuGqrxv0s",
    "AIzaSyCKSJIm14Nib0Zk0AHI8D648JpEJ9sCFkE",
    "AIzaSyDZaSOUZ2RIcB8pKPxqD-fRcSR2cGpku04",
    "AIzaSyDAtXPCWUBBTdAh6FwBvnvZPqzUlaE1C00",
    "AIzaSyDcpGeNhSObigATfhNsiKS0C1H6ekobjl0",
    "AIzaSyBJKR5hhVdQcxS7Ke-f5sJJeFB-kFyjSA4",
    "AIzaSyBaHCHnqopcCwaDba5_wvX3TNbFlKVF74o",
    "AIzaSyBJk88p2iAkwjdK0TVMQvH1r6CzVSo4bzs",
    "AIzaSyD0Rofm1mCL_juH0dMTIdhURxOgnba--5U",
    "AIzaSyDoNxCi6yqCNYufp6Gy1QgV5nPFpCtOdBg",
    "AIzaSyB4ae0lLfoJ_FNtSeox9rJtHtP8xkEWyDQ",
    "AIzaSyAMC-EZI5dVWBRXMmWQmX4YypXQUEEfdiE",
    "AIzaSyAK1WyWgYy4lCRvMguhlJ6-2LvCVKYes_Q",
    "AIzaSyDlnVsbjGDedl04cuGurAbFzpLoWZs-stA",
    "AIzaSyA9Irj23OPIJqYT7ana6kaj7jZ-LETdKms",
    "AIzaSyDOeTVpl7T2RsAltWivjYIZc8dJQ39FkR4",
    "AIzaSyB91JOYbtoa9sFPClfdLzQxQJbhNztgtDQ",
    "AIzaSyDWjzcHgAb855_8y4l9ySAPHsL2SD0wwQM",
    "AIzaSyAayryTIlnUdB49_4pSQmY6X1m_DLmJJrg",
    "AIzaSyB5NSOGX9AMdkSM0L4oV8J8svh2tXbcqfs",
    "AIzaSyCJ0pUF_6HEZNM7ZMpCZZHoxRHw3nA53WE",
    "AIzaSyCc5NDw97mS1nfPFvBXah_T55u4JusBOiA",
    "AIzaSyAlVFLpN4SaY5oob8L64aGl872xKrwjP7Q",
    "AIzaSyCxk9_Wnet_KRQQI8DdnfSkHFBRGbBSfzU",
    "AIzaSyACKhCho8uE71sG_XipvkkO_GFAAhzG4Ko",
    "AIzaSyDaBHCTumNg9IAngu45Fjrkl8i73yn62l0",
    "AIzaSyAjKPLS_wy-5Dy0P-aKmgM0VvshEwKRzGU",
    "AIzaSyBoxdg8TAXYOks8W8RoucgTDUGCZjjzCmw",
    "AIzaSyATIoR8WLKXZ-NEhT2Al66nUaojC7qYpdM",
    "AIzaSyAplPjMrxVPp0G9_eb933n72-hgIngK2HQ",
    "AIzaSyDxyy6jQ1h3o10VNr4V7QE_t9hYSEC4Rv4",
    "AIzaSyAkCYPA71dExmX3hjEcM9smQbx-oE20iG0",
    "AIzaSyCFFIZyrjmehFFYMM-hrpYfeImawF-lOGI",
    "AIzaSyDy6zgFCE1QbMwZt-lYYA-xnhaVu7obOX8",
    "AIzaSyDkEPGjPeZwwlvWz3vlsRRzcnRe1lhAWhg",
    "AIzaSyBMs-pkrDbuTxQiTQrD1jUHRR_xVhU9EU8",
    "AIzaSyB4SmafxvLzcYEYAE_IJXPYE86eikbPyQQ",
    "AIzaSyC2Mx-wzHKqv7hCIi5ng4Ts7iKexT4AwEs",
    "AIzaSyCORFlOcq-G_fqTpdG3-ZuO6Aa2MFlttSU",
    "AIzaSyDolIR2foJH_GEkTx1WkaoFYp8VZMUVdGk",
    "AIzaSyCYdQhj-bwiyTGcuwboty16ysOkAZ4kC-Q",
    "AIzaSyCVxDq9dvTlDwoz29gvomcqp7bZWtay66I",
    "AIzaSyAnvzgbE6ZyouVB0hm8popM6DdKw51Ey9k",
    "AIzaSyBXcEBwxGy7jRw9dJmoSPnQ7U43AdvWw6k",
    "AIzaSyDJ6tIExRVKM-ggfty9Wmmtu_lIlDyfxtI",
    "AIzaSyDsFqM_UbHBCqgLDBNctyOs5r71LwQdRhM",
    "AIzaSyAzihFhxGxb4EQ-Q53ICGXjKV3jFBg693k",
    "AIzaSyBNx3NM9OfmGQdT4Gi3mc-4sT7chtjHaa0",
    "AIzaSyCcZgR4BcU9BogUaouKVweGIY10qb5QJQA",
    "AIzaSyAHOFV2vmdQKlxAOZ4uxAgoTib06vzS8kc",
    "AIzaSyAI1wJqfL_2qlQJnJxJzlU7ViJfUFo7PzM",
    "AIzaSyBVk2HC4ScKC08wwmoDU-NDmnV--b55OlQ",
    "AIzaSyDIyduz-6kg2UvhNlQH3ZaRvZjuyN5mSIU",
    "AIzaSyDaeMT99VpV5lnSnOkIgUu07VAqoawRBOg",
    "AIzaSyArK9sk5tLLIVbUqmxfkUKh3zO0aLpQ-JM",
    "AIzaSyA4D1EkiyXV_2ErNHWw4o_LvK2KQaw1SqE"
]

[turso]
db_url = "libsql://analyst-workbench-database-emadarshadalam.aws-ap-south-1.turso.io"
auth_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjI1MjIwMDMsImlkIjoiMTA5NjAzY2QtYzhkZi00OTE3LWIwZTItMDgzNjFmMjFkZTUwIiwicmlkIjoiZjcxOTdhOTgtYjViZS00NmY3LTk2YmQtMWNjZjNlYTRlMWQ5In0.hU4LWQ43wbsptdK_KLF7je8RxoCKgZ20WJL5aOMpcV4NbnnQhIYe60rBGoQJzTXiIhDEoCas9Ai7LuybrhCPCQ"